---
- name: "Instalacion de php y php7.3-fpm"
  apt:
    pkg:
      - php7.3-fpm
      - php7.3-cli
      - php7.3-mysql
      - php7.3-gd
      - php7.3-curl
      - php7.3-xsl
      - php7.3-geoip
      - php7.3-ssh2
      - php7.3-gmp
      - php7.3-imap
      - phpmyadmin
    state: present

- name: Inicia servicio php7.3-fpm
  service: name=php7.3-fpm state=started enabled=yes

- name: Genera link simbolico para phpmyadmin
  file: src=/usr/share/phpmyadmin dest=/var/www/html/db owner=root group=root state=link

- name: Copia archivo de configuracion nginx para sitio default
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart {{ item }}
  with_items:
  - nginx
  - php7.3-fpm
