---
- name: Instalacion de php y php7.0-fpm
  apt: name={{ item }} state=present
  with_items:
  - php7.0-fpm
  - php7.0-cli
  - php7.0-mysql
  - php7.0-gd
  - php7.0-curl
  - php7.0-xsl
  - php7.0-geoip
  - php7.0-ssh2
  - php7.0-gmp
  - php7.0-imap
  - phpmyadmin

- name: Inicia servicio php7.0-fpm
  service: name=php7.0-fpm state=running enabled=yes

- name: Genera link simbolico para phpmyadmin
  file: src=/usr/share/phpmyadmin dest=/var/www/html/db owner=root group=root state=link

- name: Copia archivo de configuracion nginx para sitio default
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart {{ item }}
  with_items:
  - nginx
  - php7.0-fpm
